# Generated by Django 2.0.13 on 2020-01-17 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_accueil', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'accueil du blog',
                'ordering': ['date'],
            },
        ),
    ]
