# Generated by Django 2.0.13 on 2020-01-23 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_auto_20200118_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accueil',
            old_name='item',
            new_name='sujet',
        ),
        migrations.AddField(
            model_name='accueil',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
