# Generated by Django 2.0.13 on 2020-02-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_auto_20200123_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accueil',
            options={'ordering': ['sujet'], 'verbose_name': 'article'},
        ),
    ]
