# Generated by Django 2.0.13 on 2020-02-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200109_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentaire',
        ),
    ]
