# Generated by Django 2.0.13 on 2020-01-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Accueil',
        ),
    ]
