# Generated by Django 2.0.13 on 2020-01-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_django', '0002_auto_20200131_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accueil',
            new_name='MonDjango',
        ),
    ]
