# Generated by Django 2.0.13 on 2020-02-01 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mon_django', '0003_auto_20200131_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mondjango',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
