# Generated by Django 2.0.13 on 2019-09-26 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arriere_boutique', '0002_auto_20190902_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'article',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='auteur',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
