# Generated by Django 2.0.13 on 2020-01-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriere_boutique', '0005_auto_20200124_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressources',
            name='sujet',
        ),
    ]
