# Generated by Django 2.0.13 on 2020-01-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriere_boutique', '0006_remove_ressources_sujet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'item'},
        ),
    ]
