# Generated by Django 2.0.13 on 2020-02-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriere_boutique', '0007_auto_20200130_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'categorie'},
        ),
    ]
