# Generated by Django 2.0.13 on 2020-02-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriere_boutique', '0008_auto_20200216_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
