# Generated by Django 2.0.13 on 2019-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
