# Generated by Django 2.0.13 on 2019-10-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0003_auto_20191027_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='foto',
        ),
    ]
