# Generated by Django 2.0.13 on 2019-10-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0004_auto_20191028_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='foto',
            new_name='photo',
        ),
    ]
