# Generated by Django 2.0.13 on 2019-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0005_auto_20191028_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='maison/static/photos/'),
        ),
    ]
