# Generated by Django 2.0.13 on 2019-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0007_auto_20191029_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
