# Generated by Django 2.0.13 on 2020-01-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0009_auto_20200109_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumPhoto',
            new_name='Photo',
        ),
    ]
